branches:
  only:
  - master
 
nuget:
  project_feed: true
  disable_publish_on_pr: true

configuration: Release

before_build:
  - nuget-restore
	
build:
  project: SpecFlow.Retry.sln
  verbosity: normal
  
test:
  assemblies:
  - SpecFlow.Retry.Sample.dll